// !-- Do Not Hand Edit - This File is generated by CMAKE --!

#ifndef BMDAQ_CONFIG_H
#define BMDAQ_CONFIG_H 1

#define KS_VERSION_STRING "0.3.0"

#define KS_DIR "/home/yordan/Workspace/trace-cmd/ks_qtdev"

#define N_CPUS 8

#endif // CONFIG_H
