// !-- Do Not Hand Edit - This File is generated by CMAKE --!

#ifndef _KS_CONFIG_H
#define _KS_CONFIG_H

#ifdef __cplusplus

#include <QString>
#include <QList>

const QString plugins = "sched_events;xenomai_sched_events";

#endif /* __cplusplus */

#define KS_VERSION_STRING "0.5.0"

#define KS_DIR "/home/yordan/Workspace/trace-cmd_qtdev/ks_qtdev"

#define N_CPUS 8

#endif // _KS_CONFIG_H
